### ISSUE TITLE
Share some ideas how preprocessed dataset in some reasonable time?

### ISSUE THREAD

**Issue by Kakoedlinnoeslovo** [YuvalNirkin/fsgan#123]
Hi! 👐 Thank you for the amazing code and paper! ✨
 I am currently doing research on my own. I am trying to reproduce your paper. I have only one gpu and the problem is that I can't prepare IJB-C in some reasonable time, preprocessing has been running for 1 day and only 401/11777  images have been processed. Can you please share some ideas of how to preprocess the dataset in some reasonable time? Or is it possible to share the preprocessed dataset? Thank you for any help!😊
 
```
[401/11777] Processing "12776"...
=> Detecting faces in video: "12776.mp4..."
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1860/1860 [00:14<00:00, 128.39frames/s]
=> Extracting sequences from detections in video: "12776.mp4"...
```

**Comment by YuvalNirkin** [comment]
Just 29 more days to go then 😉 
Having unlimited processing power really helped this project!
Anyway due to copyright issues I can't share the preprocessed dataset, sorry.

The preprocessing pipeline is very inefficient as it is, mainly because of the face detection step.
A better approach will be to first apply a person detection step and then a face detection step on a smaller region of the image. Finally, the pose, landmarks, and segmentation models can be unified into a single model.

**Comment by Kakoedlinnoeslovo** [comment]
Hi, @YuvalNirkin, thank you for your answer! 👋 
I understood, reasonable ideas about person detection and single-model for: pose, landmarks, and segmentation. 👻

**Comment by 8secz-johndpope** [comment]
close
